COLORS = {
    "bg_primary": "#232323",
    "bg_secondary": "#2D2D2D",
    "bg_panel": "#1E1E1E",
    "bg_header": "#1A1A1A",
    "bg_header_hover": "#2A2A2A",
    "bg_group": "#2A2A2A",
    "fg_primary": "#FFFFFF",
    "fg_secondary": "#CCCCCC",
    "fg_header": "#FFFFFF",
    "fg_muted": "#888888",
    "accent": "#FF8800",
    "accent_hover": "#FF9900",
    "accent_light": "#3D2A1A",
    "success": "#4CAF50",
    "success_bg": "#1A2E1A",
    "error": "#F44336",
    "error_bg": "#2E1A1A",
    "warning": "#FF8800",
    "warning_bg": "#2E2A1A",
    "border": "#3C3C3C",
    "border_light": "#4A4A4A",
    "progress_bg": "#3C3C3C",
    "progress_fill": "#FF8800",
    "button_bg": "#3C3C3C",
    "button_hover": "#4A4A4A",
    "button_active": "#2A2A2A",
    "category_document": "#FF8800",
    "category_audio": "#FF9900",
    "category_image": "#FFAA00",
    "category_video": "#FF7700",
    "drop_zone": "#2A2A2A",
    "drop_zone_active": "#3D2A1A",
}

FONTS = {
    "title": ("Segoe UI", 22, "bold"),
    "heading": ("Segoe UI", 18, "bold"),
    "body": ("Segoe UI", 14),
    "body_bold": ("Segoe UI", 14, "bold"),
    "small": ("Segoe UI", 13),
    "small_bold": ("Segoe UI", 13, "bold"),
    "mono": ("Consolas", 13),
}

SIZES = {
    "border_radius": 4,
    "border_width": 1,
    "padding_sm": 4,
    "padding_md": 8,
    "padding_lg": 16,
    "padding_xl": 24,
    "icon_size": 20,
    "button_height": 32,
    "min_width": 1100,
    "min_height": 700,
}
