COLORS = {
    "bg_primary": "#F0F0F0",
    "bg_secondary": "#E4E4E4",
    "bg_panel": "#FFFFFF",
    "bg_header": "#2B579A",
    "bg_header_hover": "#3B67AA",
    "bg_group": "#F5F5F5",
    "fg_primary": "#1E1E1E",
    "fg_secondary": "#555555",
    "fg_header": "#FFFFFF",
    "fg_muted": "#888888",
    "accent": "#2B579A",
    "accent_hover": "#1B478A",
    "accent_light": "#D6E4F0",
    "success": "#2E7D32",
    "success_bg": "#E8F5E9",
    "error": "#C62828",
    "error_bg": "#FFEBEE",
    "warning": "#F57F17",
    "warning_bg": "#FFF8E1",
    "border": "#C0C0C0",
    "border_light": "#D8D8D8",
    "progress_bg": "#E0E0E0",
    "progress_fill": "#2B579A",
    "button_bg": "#E1E1E1",
    "button_hover": "#D0D0D0",
    "button_active": "#C0C0C0",
    "category_document": "#2B579A",
    "category_audio": "#7B1FA2",
    "category_image": "#00838F",
    "category_video": "#E65100",
}

FONTS = {
    "title": ("Segoe UI", 16, "bold"),
    "heading": ("Segoe UI", 13, "bold"),
    "body": ("Segoe UI", 11),
    "body_bold": ("Segoe UI", 11, "bold"),
    "small": ("Segoe UI", 9),
    "small_bold": ("Segoe UI", 9, "bold"),
    "mono": ("Consolas", 10),
}

SIZES = {
    "border_radius": 4,
    "border_width": 1,
    "padding_sm": 4,
    "padding_md": 8,
    "padding_lg": 16,
    "padding_xl": 24,
    "icon_size": 20,
    "button_height": 32,
    "min_width": 900,
    "min_height": 600,
}
